### PR TITLE
Enhancements to FastGeoAPI with Keycloak and PostgreSQL Integration

### PR DESCRIPTION
**Pull request by Youssef-Harby**
This pull request introduces several improvements and enhancements to the FastGeoAPI project. 
## Changes :

1. **Keycloak Predefined RealmJSON Import at Startup with Docker Compose File**: This update allows for the import of a predefined realmJSON file at startup, facilitated through the use of a Docker compose file.

2. **Upgrade Keycloak and Make it More Reliable with PostgreSQL**: Keycloak has been upgraded for better reliability. Additionally, it has been configured to work more effectively with PostgreSQL.

3. **Fix Postman Collections to Use Port 5000 Instead of 8000**: The Postman collections have been fixed to use port 5000 instead of 8000.

4. **Change Location of Pygeoapi Realm**: The location of the Pygeoapi realm has been altered.

5. **Add the .env File for Docker-compose**: A .env file for Docker-compose has been added to the repository.

6. **Upgrade to the New openid-configuration URL from Keycloak**: The URL for openid-configuration from Keycloak has been updated to the latest version.

7. **Change Postman Collections to the New Keycloak openid-configuration URLs**: The Postman collections have been updated to use the new openid-configuration URLs from Keycloak.

8. **Add the Health Check and Keycloak Start Instead of start-dev prod ready**: A health check has been added and Keycloak now starts using the production-ready configuration instead of the development configuration.

9. **Replace client_secret to the Predefined One**: The client_secret has been replaced with a predefined one.

10. **Notes for New Keycloak and PostgreSQL Updates**: Notes have been added for new updates to Keycloak and PostgreSQL.

These changes contribute to the overall improvement of the FastGeoAPI project, enhancing its reliability, effectiveness, and ease of use. The changes made to Keycloak and PostgreSQL integration, in particular, should greatly enhance the overall functionality of the system.

### CODE REVIEW

**Comment by francbartoli** [comment]
@Youssef-Harby looks good to me, there are a couple of pre-commit failing checks. Would you like to fix them? Btw safety is unrelated and I will cover it before the FOSS4G

**Review by francbartoli — APPROVED** [review]

**Review by francbartoli — CHANGES_REQUESTED** [review]
All tests are now failing

**Comment by Youssef-Harby** [comment]
Thank you for your feedback, @francbartoli . I have addressed the pre-commit failing checks as per your suggestion. Here are the updates:

- Upgraded packages and pygeoapi to the latest 
- Imported APP instead of app to accommodate the new pygeoapi version 0.16.dev0 
- Reformatted the code with prettier and removed extra spaces 

Please let me know if there are any other changes needed. I'm ready to make any required

**Comment by francbartoli** [comment]
well done @Youssef-Harby! Thanks

**Comment by francbartoli** [comment]
@Youssef-Harby the failure is unrelated to your PR, it's due to this package https://github.com/cjolowicz/nox-poetry using a deprecated option `--dev`. I'll try to make a patch for that, meantime I'm going to merge your great contribution

**Pull request merged**
